export const OPERATION_START = 'OPERATION_START';
export const OPERATION_FAIL = 'OPERATION_FAIL';

export const SEARCHING_START = 'SEARCHING_START';
export const SEARCHING_FAIL = 'SEARCHING_FAIL';
export const SEARCHING_SUCCESS = 'SEARCHING_SUCCESS';
export const SEARCHING_INIT = 'SEARCHING_INIT';

export const SET_REPORT_NAME = 'SET_REPORT_NAME';

export const SEARCHING_UPDATE_ITEM = 'SEARCHING_UPDATE_ITEM';
export const SEARCHING_REMOVE_ITEM = 'SEARCHING_REMOVE_ITEM';

export const SAVE_CHECK_SUCCESS = 'SAVE_CHECK_SUCCESS';
export const DELETE_CHECK_SUCCESS = 'DELETE_CHECK_SUCCESS';
export const SET_CHECK = 'SET_CHECK';
